# Сервис блога [posts]
@hostname = http://localhost
@port = 3666
@prefix = api
@host = {{hostname}}:{{port}}/{{prefix}}
@parentPath = posts
@contentType = application/json
@POST_ID = 1c3e0eae-fad2-4beb-9bd8-8baac7aabfff
@USER_ID = 2a83efd4-07da-42c5-ad2f-339dcb1c3352
# @CONTENT_ID =26c60e02-6db6-49b2-ba5f-9024a7fb3941
@CONTENT_ID =e9ed6476-be0f-4495-a4f3-a8a16793d82d


### Все посты
GET {{host}}/{{parentPath}} HTTP/1.1

### Посты с фильтром
@page= 1
@limit= 10
@type= VIDEO
@sortDirection = desc
GET {{host}}/{{parentPath}}?page={{page}}&limit={{limit}}&sortDirection={{sortDirection}}&type={{type}} HTTP/1.1

### Создать видео пост
POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}

{
  "type": "video",
  "content": {
    "title": "Мой др 33",
    "url": "https://www.youtube.com/watch?v=JU79n3yU1aA"
  },
  "tags": ["hb", "party"],
  "author": "df191215-1f3c-407d-96b2-390bdfae1961"
}


### Обновить пост

PATCH  {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}

{
  "content": {
    "title": "Мой др 33",
    "url": "https://www.youtube.com/watch?v=JU79n3yU1aA"
  },
  "author": "df191215-1f3c-407d-96b2-390bdfae1961"
}

### Получить все типы постов
GET  {{host}}/{{parentPath}}/types HTTP/1.1